### ISSUE TITLE
ciw not deleting text

### ISSUE THREAD

**Issue by felixSchl** [hchbaw/opp.zsh#15]
I must be doing something wrong, but when I enter some text and go into normal mode, then type `ciw` with my cursor over a word, the cursor will simply jump to the beginning of the line and the word remains in tact. It does, however, put me into insert mode. I am using this plugin in conjunction with `oh-my-zsh`'s `vi-mode` plugin.

**Comment by hchbaw** [comment]
Could you plese show your `~/.zshrc`?

**Comment by felixSchl** [comment]
Of course. I am just getting started with `zsh`, so there's not much to it:

```zsh
source ~/antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle github
antigen bundle node
antigen bundle python
antigen bundle command-not-found
antigen bundle brew
antigen bundle cabal
antigen bundle bower
antigen bundle vi-mode
antigen bundle hchbaw/opp.zsh
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle nojhan/liquidprompt
antigen bundle mollifier/cd-gitroot
antigen bundle jocelynmallon/zshmarks

# git-root
alias cdu='cd-gitroot'

# Liquid prompt
LP_ENABLE_TIME=1
LP_USER_ALWAYS=1

antigen apply

export KEYTIMEOUT=1
```

**Comment by hchbaw** [comment]
Thank you for your help!

I've pushed the fix. Could you confirm?

**Comment by felixSchl** [comment]
Yes, I can confirm it's working - good work! Thanks
