### ISSUE TITLE
~ (tilde) is not vim conform

### ISSUE THREAD

**Issue by martong** [hchbaw/opp.zsh#5]
In vim if you press ~ only the character at the cursor will have a swapped case. You cannot provide any additonal text-object after you pressed ~. 
~iw in vim results the following  (^ indicates where the cursor is, -> indicates the result) :
asdf  -> asDwf
==^

~iw in opp.zsh results the following:
asdf  -> ASDF
==^

I think pressing ~ just simply should swap the case of the letter under the current cursor position. 
This should be the expected behaviour when ~ pressed:
asdf -> asDf
==^

asdf  -> ASDF can be achieved with gUiw .

What is your opinion?
Many Thanks,
Gábor

**Comment by rosshadden** [comment]
Oh wow, I thought for all these years that `~` was just not an implemented feature in `vi-mode` or `opp.zsh`.  I was looking into how to make it function as it does in vim and found this issue.  It's nice to know it _is_ implemented, just differently.

By the way @hchbaw, if you use `g~` in vim it is an operator like you would think. `g~iw`, etc.

**Comment by hchbaw** [comment]
Thanks @rosshadden for your work!
